[phases.setup]
nixPkgs = ['bun', 'nodejs']

[phases.install]
cmd = 'bun install'

[phases.build]
cmd = 'bun run build:counting && bun run build:web'

[phases.start]
cmd = 'bun run start'

[variables]
NODE_ENV = 'production'